# Generated by Django 4.2.4 on 2024-02-29 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplications',
            name='resume',
            field=models.FileField(upload_to='resume/'),
        ),
    ]
