# Generated by Django 4.2.4 on 2024-03-02 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_candidateapplications_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateapplications',
            name='status',
            field=models.CharField(choices=[('pandding', 'pandding'), ('selected', 'selected')], default='pending', max_length=20),
        ),
    ]
